---
version: 2.1

commands:
  shared_steps:
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          key: tally-{{ checksum "Gemfile.lock" }}

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: Bundle Install
          command: |
            ./bin/bundle config set path 'vendor/bundle'
            ./bin/bundle check || ./bin/bundle install --jobs 4 --retry 3

      - save_cache:
          name: Store bundle cache
          key: tally-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

default_job: &default_job
  working_directory: ~/repo
  steps:
    - shared_steps

    - run:
        name: "Rails DB Migrate"
        command: |
          bundle exec rails db:migrate

    - run:
        name: "Rubocop"
        command: bundle exec rubocop



    - run:
        name: "RSpec"
        command: |
          bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          spec/

    - store_test_results:
        path: /tmp/test-results

jobs:
  ruby_25:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.5-stretch-node
        environment:
          RAILS_ENV: test
      - image: redis:4.0

  ruby_26:
    <<: *default_job
    docker:
      - image: circleci/ruby:2.6-stretch-node
        environment:
          RAILS_ENV: test
      - image: redis:4.0


workflows:
  version: 2
  rubies:
    jobs:
      - ruby_25
      - ruby_26

