---
version: 2.1

commands:
  shared_steps:
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          key: v4-tally-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: |
            gem uninstall bundler
            gem install bundler -v=2.1.2
            bundle config set path 'vendor/bundle'
            bundle install
            bundle exec appraisal install

      - save_cache:
          name: Store bundle cache
          key: v4-tally-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

default_job: &default_job
  working_directory: ~/repo
  steps:
    - shared_steps

    - run:
        name: "Rails DB Migrate"
        command: |
          bundle exec rails db:migrate

    - run:
        name: "Rubocop"
        command: bundle exec rubocop

    - run:
        name: "RSpec"
        command: |
          bundle exec appraisal rspec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress

    - store_test_results:
        path: /tmp/test-results

jobs:
  ruby_30:
    <<: *default_job
    docker:
      - image: cimg/ruby:3.0.4-node
        environment:
          RAILS_ENV: test
      - image: redis:7.0.5

  ruby_31:
    <<: *default_job
    docker:
      - image: cimg/ruby:3.1.3-node
        environment:
          RAILS_ENV: test
      - image: redis:7.0.5


workflows:
  version: 2
  rubies:
    jobs:
      - ruby_30
      - ruby_31

