version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.4-node-browsers
        environment:
          RAILS_ENV: test
      - image: redis:3.2
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          name: Restore bundle cache
          keys:
            - zig-tally-{{ checksum "Gemfile.lock" }}
            - zig-tally-

      # Bundle install dependencies
      - run:
          name: Bundle Install
          command: bin/bundle check --path vendor/bundle ||  bin/bundle install --path vendor/bundle --jobs 4 --retry 3

      - save_cache:
          name: Store bundle cache
          key: zig-tally-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Migrate
          environment:
            - RAILS_ENV: test
          command: |
            bundle exec rails db:migrate
            bundle exec rails db:seed

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - type: shell
        command:
          bundle exec rubocop

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
