version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6-stretch-node
        environment:
          RAILS_ENV: test
      - image: redis:4.0
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          name: Restore bundle cache
          keys:
            - tally-{{ checksum "Gemfile.lock" }}
            - tally-

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Bundle install dependencies
      - run:
          name: Bundle Install
          command: bin/bundle check --path vendor/bundle ||  bin/bundle install --path vendor/bundle --jobs 4 --retry 3

      - save_cache:
          name: Store bundle cache
          key: tally-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Migrate
          environment:
            - RAILS_ENV: test
          command: |
            bundle exec rails db:migrate
            bundle exec rails db:seed

      - type: shell
        command:
          bundle exec rubocop

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            spec/

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
